import type { FractionValue, Rational } from './rational.ts';

/**
 * Bracket style hierarchy for nested algebraic groupings.
 * Level 1: Round () | Level 2: Curly {} | Level 3: Square []
 */
export type BracketType = 'round' | 'curly' | 'square';

/**
 * Supported binary algebraic operators.
 */
export type BinaryOperator = '+' | '-' | '*' | '/';

/**
 * Node types in the algebraic AST.
 */
export type ASTNodeType = 'variable' | 'constant' | 'binary' | 'fraction' | 'group' | 'unary';

/**
 * Unified AST Node representing terms, operations, fractions, and groupings.
 */
export interface ASTNode {
  id: string;
  type: ASTNodeType;
  op?: BinaryOperator;
  left?: ASTNode;
  right?: ASTNode;
  numerator?: ASTNode;
  denominator?: ASTNode;
  value?: number;
  fractionValue?: FractionValue;
  name?: string;
  inner?: ASTNode;
  operand?: ASTNode;
  bracketType?: BracketType;
  implicit?: boolean; // e.g., 2x or 13(3m-7)
  isReducible?: boolean; // For unsimplified fractions like 78/9
  unsimplifiedFraction?: FractionValue;
}

/**
 * Complete state of an algebraic equation being solved.
 */
export interface EquationState {
  id: string;
  lhs: ASTNode;
  rhs: ASTNode;
  targetVariable: string;
  solution: FractionValue;
  difficultyLevel?: number;
  initialEquationStr?: string;
  stepCount: number;
  isSolved: boolean;
}

/**
 * Result of user move validation.
 */
export interface ValidationResult {
  isValid: boolean;
  peelableNodeId?: string;
  requiredInverseOp?: BinaryOperator;
  errorCode?:
    | 'TRAPPED_IN_BRACKET'
    | 'TRAPPED_IN_NUMERATOR'
    | 'TRAPPED_IN_FACTOR'
    | 'VARIABLE_NODE_SELECTED'
    | 'WRONG_SIDE'
    | 'NOT_PEELABLE';
  errorMessage?: string;
  blockingAncestorId?: string;
  blockingDescription?: string;
}

/**
 * Result of applying an inverse operation move.
 */
export interface MoveResult {
  success: boolean;
  newEquation: EquationState;
  message: string;
}

/**
 * Simplification opportunity found in AST.
 */
export interface SimplificationOpportunity {
  nodeId: string;
  type: 'FRACTION_REDUCE' | 'CONSTANT_FOLD' | 'UNWRAP_GROUP';
  originalText: string;
  simplifiedText: string;
  simplifiedNode: ASTNode;
}

/**
 * Single step in an automated solver trace.
 */
export interface SolverStep {
  stepIndex: number;
  nodeIdToMove: string;
  actionType: 'MOVE_TERM' | 'SIMPLIFY_FRACTION' | 'CONSTANT_FOLD' | 'UNPACK_GROUP';
  inverseOp?: BinaryOperator;
  operandValue?: Rational;
  explanation: string;
  resultingLHS: ASTNode;
  resultingRHS: Rational;
  equationLatex: string;
  equationInfix: string;
}

/**
 * Solvability proof & trace generated by the solver.
 */
export interface SolvabilityProof {
  isSolvable: boolean;
  targetVariable: string;
  verifiedSolution: Rational;
  stepsCount: number;
  steps: SolverStep[];
  validationErrors: string[];
}

/**
 * Handcrafted preset puzzle definition.
 */
export interface LevelPreset {
  id: string;
  title: string;
  description: string;
  equationStr: string;
  level: number;
  targetVariable: string;
  solution: FractionValue;
  hints: string[];
}

/**
 * Difficulty profile configuration.
 */
export interface DifficultyProfile {
  level: number;
  name: string;
  description: string;
  maxPeelingDepth: number;
  allowedBracketTiers: BracketType[];
  allowFractions: boolean;
  allowReducibleRHS: boolean;
  variablePool: string[];
  coeffRange: [number, number];
  divisorRange: [number, number];
  solutionRange: [number, number];
}
